# Generated by Django 3.2.16 on 2022-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20221124_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(choices=[('UNRATED', 'Unrated'), ('TV-PG', 'TV-PG'), ('TV-G', 'TV-G')], default='UNRATED', max_length=7),
        ),
    ]
