# Generated by Django 3.2.16 on 2022-11-24 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(choices=[('UNRATED', 'Unrated'), ('TV-PG', 'TV-PG'), ('TV-G', 'TV-G'), ('TV-R', 'TV-R'), ('TV-X', 'TV-X')], default='UNRATED', max_length=7),
        ),
    ]
